version: '3.7'

services:
  management1:
    container_name: management1
    image: mysql/mysql-cluster:7.6.12
    networks:
      cluster:
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
      - ./conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndb_mgmd

  ndb1:
    container_name: ndb1
    image: mysql/mysql-cluster:7.6.12
    networks:
      cluster:
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
      - ./conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd

  ndb2:
    container_name: ndb2
    image: mysql/mysql-cluster:7.6.12
    networks:
      cluster:
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
      - ./conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd

  mysql1:
    container_name: mysql1
    image: mysql/mysql-cluster:7.6.12
    networks:
      cluster:
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
      - ./conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: mysqld
    ports:
      - 33306:3306
    depends_on:
      - management1
      - ndb1
      - ndb2

networks:
  cluster:

volumes:
  mysql-cluster-data:

